import type { Severity } from "@/lib/scan/types";
import { sevHex, sevTint, sevLabel } from "./shared";

export function BrandMark({ size = 22 }: { size?: number }) {
  return (
    <span
      className="flex shrink-0 items-center justify-center rounded-md bg-ink"
      style={{ width: size, height: size }}
    >
      <span
        className="rotate-45 rounded-xs bg-brand-500"
        style={{ width: size * 0.4, height: size * 0.4 }}
      />
    </span>
  );
}

export function SectionKicker({ children }: { children: React.ReactNode }) {
  return (
    <span className="text-[10px] font-semibold tracking-[0.2em] text-brand-600 uppercase">
      {children}
    </span>
  );
}

export function SectionKickerMuted({ children }: { children: React.ReactNode }) {
  return (
    <span className="text-[10px] font-semibold tracking-[0.2em] text-muted uppercase">
      {children}
    </span>
  );
}

export function FieldLabel({ children, tone }: { children: React.ReactNode; tone?: "brand" }) {
  return (
    <div
      className={`text-[8.5px] font-semibold tracking-[0.13em] uppercase ${
        tone === "brand" ? "text-brand-600" : "text-muted"
      }`}
    >
      {children}
    </div>
  );
}

export function PageShell({
  children,
  page,
  host,
}: {
  children: React.ReactNode;
  page: number;
  host: string;
}) {
  return (
    <section className="ac-page flex min-h-264 w-204 flex-col rounded-2xl bg-card px-[0.62in] py-12 shadow-card">
      <div className="flex flex-1 flex-col">{children}</div>
      <PageFooter page={page} host={host} />
    </section>
  );
}

function PageFooter({ page, host }: { page: number; host: string }) {
  return (
    <div className="mt-auto flex items-center justify-between border-t border-line pt-3 text-[10px] font-medium text-muted">
      <span className="flex items-center gap-1.5">
        <BrandMark size={14} />
        <span className="text-ink-soft">
          Generated by <b className="font-bold text-ink">AccessCheck</b>
        </span>
      </span>
      <span className="truncate px-2 font-mono text-[9.5px]">{host}</span>
      <span>WCAG 2.1 · Page {page} / 3</span>
    </div>
  );
}

export function MiniHeader({ host }: { host: string }) {
  return (
    <div className="flex items-center justify-between border-b border-line pb-3">
      <div className="flex items-center gap-2.5">
        <BrandMark size={24} />
        <span className="text-[13px] font-bold text-ink">AccessCheck</span>
      </div>
      <span className="truncate pl-3 font-mono text-[10.5px] text-muted">
        Accessibility Report · {host}
      </span>
    </div>
  );
}

export function LegendChip({ sev, count }: { sev: Severity; count: number }) {
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-line bg-card px-3 py-1.5 text-[11px] font-semibold text-ink">
      <span className="size-2 rounded-full" style={{ background: sevHex[sev] }} />
      {sevLabel[sev]} <b className="font-medium text-muted">{count}</b>
    </span>
  );
}

export function GroupHeading({ sev, count }: { sev: Severity; count: number }) {
  return (
    <div className="flex items-center gap-2.5">
      <span className="size-2.5 rounded-[3px]" style={{ background: sevHex[sev] }} />
      <span className="text-[13px] font-semibold text-ink">{sevLabel[sev]}</span>
      <span
        className="rounded-full px-2 py-0.5 text-[10px] font-semibold"
        style={{ color: sevHex[sev], background: sevTint[sev] }}
      >
        {count} issue{count > 1 ? "s" : ""}
      </span>
      <span className="h-px flex-1 bg-line" />
    </div>
  );
}

export function HeroRing({ value }: { value: number }) {
  const r = 58;
  const circ = 2 * Math.PI * r;
  const offset = circ * (1 - value / 100);
  return (
    <div className="relative size-34.5">
      <svg width="138" height="138" viewBox="0 0 138 138">
        <circle cx="69" cy="69" r={r} fill="none" stroke="rgba(255,255,255,.18)" strokeWidth="11" />
        <circle
          cx="69"
          cy="69"
          r={r}
          fill="none"
          stroke="#bcd2ff"
          strokeWidth="11"
          strokeLinecap="round"
          strokeDasharray={circ}
          strokeDashoffset={offset}
          transform="rotate(-90 69 69)"
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-[46px] leading-none font-bold text-white">{value}</span>
        <span className="mt-0.5 text-[10px] font-semibold tracking-wide text-white/60">
          OUT OF 100
        </span>
      </div>
    </div>
  );
}
